### ISSUE TITLE
Enhancement Request - Completed Avatars

### ISSUE THREAD

**Issue by ElenaK7** [Venomed/SkyforgeAelinetScraper#10]
Hi again.

If you get time at some point wondered if you would be able to add completed avatars to the data pulled for each person.  I was looking at aelinet and saw the avatar fights get listed in completed instances for players just as distortions do.

With the Mechanoid invasion that's currently with us we're busily trying to arrange runs to get all eligible members their books and it would have been really handy to know up front without having to try and get everyone to reply to posts about it who needs it and who has it already.  An aid to planning.

Thanks

Elena

**Comment by Maverik** [comment]
That's super easy to expose! I already have the data and I just need to add a column!
