### ISSUE TITLE
InvalidOperationException in new build

### ISSUE THREAD

**Issue by ElenaK7** [Venomed/SkyforgeAelinetScraper#13]
![error capture](https://cloud.githubusercontent.com/assets/18260852/15660197/b68b7438-26d0-11e6-96ef-e6e848bdcbe4.PNG)

Newest version with build stats throws an exception when run.  Snapshot of error details attached.

**Comment by Maverik** [comment]
Same as #14, closed by 04c7b0825096f5bb9ac8e498fa8ebe2bb6ad0436
