### ISSUE TITLE
Aggregate Exception in Akonita update

### ISSUE THREAD

**Issue by ElenaK7** [Venomed/SkyforgeAelinetScraper#14]
Saw there was a new download so gave it a whirl but got this crash:

![tool-crash-akonita-version-capture](https://cloud.githubusercontent.com/assets/18260852/16346874/7ef23884-3a41-11e6-923f-25749b2c4c6c.jpg)

does not look identical to the previous issue I raised but as it says aggregate not sure if in fact the previous issue still exists and another has appeared now as well.

**Comment by Maverik** [comment]
That's basically saying there's no login page from Aelinet. It appears to happen sometimes but goes away on it own. I'm not sure what to do about it as it's a server side issue from my current understanding.

**Comment by ElenaK7** [comment]
As requested tried running again.  Aggregate exception again although only after 5 mins of processing - it appeared to successfully read through all pantheon members (all the way down to Z listed on display) and dies after that.

**Comment by ElenaK7** [comment]
Further detail following today's discussion.  Tried 3 more runs with different setting on the additional detail options:

Both false - succeeds
Avatar = true, Statistics = false - fails with aggregate exception
Avatar = false, Statistics = true - succeeds

So it appears the issue relates to the avatar section specifically.

**Comment by Maverik** [comment]
Thank you Elena for keeping this issue in sync with our discussions

**Comment by Maverik** [comment]
This turned out to be another "Mod" account quirk. The code was trying to pull out "Active Class" stat during `SetMemberStatisticsTab` call.
