### ISSUE TITLE
Tool doesn't support proxy for internet access

### ISSUE THREAD

**Issue by Maverik** [Venomed/SkyforgeAelinetScraper#27]
The issue is to document the problem faced by [The Vortex](https://eu.portal.sf.my.com/wall/72065290619430723) in [comment ](https://eu.portal.sf.my.com/comments/564ca211ac7218cd94eb3e5a/61?page=4) which turned out to be likely an issue with lack of proxy support.

**Comment by thevortex42** [comment]
Even with the proxy activated in the script I get the same error. Dumping the contents of the HTML file received shows that there is no content whatsoever. Tried it on another computer in the same environment, same error. So it is not a PC but a network problem.

**Comment by Maverik** [comment]
Hmm I'm confused if the proxy code isn't working perhaps or if that particular environment is blocking Aelinet access somehow?

**Comment by thevortex42** [comment]
I can access the Aelinet via Browser without any problems, so it isn't blocked in any way. My guess is still the proxy.
I even used other URIs as Target for testing and they all returned blank results.

**Comment by Maverik** [comment]
I get the feeling they've changed some code on Aelinet. Its acting weird in my browser even. Going to https://eu.portal.sf.my.com normally presented you with a login and you'd see skyforge news. Right now it's sending me to account.my.com & if i login and try again to Aelinet in fresh browser setup, I get "ERROR TOO MANY REDIRECTS". They've messed something up!

**Comment by Maverik** [comment]
It appears that Aelinet is back to its normal self now. I've also confirmed that proxy settings are in fact working so this appears to be out of my control.
