### ISSUE TITLE
NRE thrown when the player is a moderator account

### ISSUE THREAD

**Issue by ElenaK7** [Venomed/SkyforgeAelinetScraper#7]
As discussed in game today I've run into this error which I think may be caused by a pantheon member who does not have their character details displayed on the aelinet.  As requested I attach a couple of snapshots of the error location in code and the stack trace.
![null-error-snap1-capture](https://cloud.githubusercontent.com/assets/18260852/14247232/ac3cf21a-fa64-11e5-97b4-9ccc7e1d2992.jpg)
![null-error-snap2-trace-capture](https://cloud.githubusercontent.com/assets/18260852/14247237/b111b028-fa64-11e5-9a50-49d9a629b8e5.jpg).

Thanks in advance for any help you can give.

**Comment by Maverik** [comment]
Just to add for future reference, this specific case is only applicable to Moderator accounts or I suppose other staff members using same account for game & their staff duties. Not something I expected but oh well!
